name: 🚀Deploy App...
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉Get rep src code
        uses: actions/checkout@v3
      - name: ✨npm install
        run: npm ci
      - name: 🛠️ Testing app...
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 🎉Get rep src code
        uses: actions/checkout@v3
      - name: ✨npm install
        run: npm ci
      - name: 🐛 Lint tests app...
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: 🎉Get rep src code
        uses: actions/checkout@v3
      - name: ✨ npm install
        run: npm ci
      - name: 🚀Build app...
        run: npm run build
